### ISSUE TITLE
Assert failed: >! used not in (go ...) block

### ISSUE THREAD

**Issue by grinderrz** [bobby/ring-sse#5]
Sadly, my recent PR was broken. It results in
```Assert failed: >! used not in (go ...) block```

According to [Go Block Best Practices](https://github.com/clojure/core.async/wiki/Go-Block-Best-Practices#unsupported-constructs-and-other-limitations-in-go-blocks) >! may not be used inside a function. But it was exactly what I was trying to do.

**Comment by bobby** [comment]
Ugh, sorry, should have looked more carefully at this.  Of course, that's why I had originally used `async/put!`.

Yes, making send-event a macro makes sense.  I'll test #6 locally (and perhaps add an integration test or two :-)
